defaultContentLanguage = "zh-tw"
enableRobotsTXT = true
baseURL = "https://boyan1001.github.io/"
category = "categories"
tag = "tags"
summaryLength = 30

[pagination]
    pagerSize = 10

[outputs]
    home = ["HTML", "RSS", "JSON"]