disabled = false
languageCode = "zh-tw"
languageName = "中文"
weight = 1
title = "Toast Coding"

[params]
displayName = "中文"
isoCode = "zh-tw"
rtl = false
dateFormat = "2006年1月2日"
logo = "toast_icon.png"
secondaryLogo = "toast_icon.png"
description = "This is a blog of Toast"

["params.author"]
image = "toast.png"
name = "Toast"
headline = "分享知識、生活和其他的部落客"
bio = "Toast 是一位分享知識、生活和其他的部落客。他也是台灣的一名學生。"
links = [
    {email = "cby931001@gmail.com"},
    {github = "https://github.com/boyan1001"},
    {linkedin = "https://www.linkedin.com/in/cby931001/"}
]